# Forever Fractal Validation Configuration

# Vector Quantization Parameters
vector_quantization:
  epsilon_q: 0.001  # Minimum spacing between quantized states
  dimension: 3      # Vector dimension
  decay_power: 2.0  # Alpha parameter
  terms: 50         # Number of terms in fractal function

# Triplet Coherence Rules
triplet_coherence:
  min_coherence: 0.7
  lambda_1: 0.6     # Phase weight
  lambda_2: 0.4     # Entropy weight
  temporal_bound: 3600  # 1 hour in seconds

# Matrix Correction Parameters
matrix_correction:
  weights: [1.0, 0.5, 0.25]
  entropy_bounds:
    low: 0.1
    high: 0.9
  z_score:
    window: 10
    threshold: 2.0

# Profit Allocation Rules
profit_allocation:
  min_delta: 0.001
  echo_threshold: 3
  reentry_cooldown: 300  # 5 minutes

# Recursive Propagation
recursive_propagation:
  min_entropy_increase: 0.01
  min_coherence_preserve: 0.8
  spectral_window: 86400  # 24 hours

# Integration Parameters
integration:
  rittle:
    ring_size: 512
    profit_threshold: 0.02
    volume_weight: 0.3
  ncco:
    pattern_window: 100
    coherence_threshold: 0.7
    profit_bucket_size: 0.01

# ALIF Unitizer Configuration
alif_unitizer:
  cache_size: 1000
  max_depth: 2
  min_price_change: 0.001
  parallel_processing: true
  entropy_threshold: 0.7
  pattern_vector_size: 8
  integration_window: 100

# Ferrous Management System
ferrous_management:
  alignment_threshold: 0.1
  wheel_alignment_window: 50
  depth_sync_threshold: 0.05
  entropy_sync_threshold: 0.1
  phase_sync_threshold: 0.15
  recursive_depth_limit: 8

# Test Suite Configuration
test_suites:
  vector_validation:
    samples: 1000
    fft_check: true
    lattice_validation: true
    
  triplet_matching:
    synthetic_triplets: 100
    real_triplets: 50
    collapse_detection: true
    
  profit_flow:
    simulation_time: 3600
    bucket_count: 100
    echo_detection: true
    
  recursive_stability:
    stress_test_vectors: 50
    entropy_tracking: true
    spectral_analysis: true
    
  alif_integration:
    test_vectors: 100
    ferrous_alignment: true
    recursive_propagation: true

# Performance Thresholds
performance:
  max_memory_usage: 1024  # MB
  max_cpu_usage: 80      # Percent
  max_latency: 100       # ms
  min_throughput: 1000   # operations/second 