# Matrix Response Paths Configuration
# =================================

# ZPE Risk Response
zpe_risk:
  fallback_strategy: cooldown_abort
  max_retries: 2
  cooldown_period: 0.5  # seconds
  severity_threshold: 0.9
  actions:
    - type: block_flash
      duration: 1.0
    - type: clear_memory
      scope: all
    - type: reset_matrix
      target: matrix_safe

# Drift Loop Response
drift_loop:
  fallback_strategy: entropy_realign
  max_retries: 3
  severity_threshold: 0.6
  actions:
    - type: phase_correction
      target_angle: 3.14159  # π
    - type: memory_rebalance
      scope: recent
    - type: update_matrix
      target: entropy_realign

# Phase Correction Response
phase_correction:
  fallback_strategy: matrix_safe
  max_retries: 1
  actions:
    - type: adjust_phase
      tolerance: 0.1
    - type: verify_stability
      threshold: 0.8

# Matrix States
matrix_states:
  matrix_safe:
    description: "Normal operation state"
    allowed_actions:
      - flash
      - memory_access
      - phase_adjustment
    stability_threshold: 0.7

  cooldown_abort:
    description: "Emergency cooldown state"
    allowed_actions:
      - memory_clear
      - phase_reset
    stability_threshold: 0.9

  entropy_realign:
    description: "Entropy correction state"
    allowed_actions:
      - phase_correction
      - memory_rebalance
    stability_threshold: 0.8

# Stability Thresholds
stability_thresholds:
  binding_energy:
    critical: 5.0
    warning: 6.0
    safe: 7.0

  phase_drift:
    critical: 0.3
    warning: 0.2
    safe: 0.1

  entropy_zscore:
    critical: 2.5
    warning: 1.5
    safe: 1.0

# Memory Management
memory_management:
  decay_rate: 0.015
  base_value: 100.0
  refresh_threshold: 0.5
  max_history_size: 1000

# Phase Shell Configuration
phase_shells:
  symmetry:
    angle_range: [3.04159, 3.24159]  # π ± 0.1
    stability_factor: 0.5

  drift_positive:
    angle_range: [3.24159, 6.28319]  # π + 0.1 to 2π
    stability_factor: 0.8

  drift_negative:
    angle_range: [0.0, 3.04159]  # 0 to π - 0.1
    stability_factor: 0.8 