fractal_hive:
  # System-wide configuration
  system:
    max_pods: 100
    health_check_interval: 5.0
    max_cpu_percent: 80.0
    max_memory_percent: 70.0
    snapshot_interval: 3600  # 1 hour
    critical_alert_threshold: 0.9

  # Pod lifecycle management
  pod_management:
    mutation_rate: 0.05
    crossover_rate: 0.7
    selection_pressure: 0.8
    min_pod_lifetime: 3600  # 1 hour
    max_pod_lifetime: 86400  # 24 hours
    resource_threshold: 0.8
    diversity_quota: 0.2  # 20% of pods should be exploratory

  # Evolution engine configuration
  evolution:
    mutation_boundaries:
      core_math:
        max_operations: 1000
        max_complexity: 0.8
        allowed_variants:
          - shannon
          - renyi
          - tsallis
          - quantum
      indicators:
        max_count: 10
        max_parameters: 5
        allowed_types:
          - rsi
          - macd
          - bollinger
          - stochastic
          - custom
      strategy:
        max_parameters: 20
        max_rules: 50
        allowed_actions:
          - buy
          - sell
          - hold
          - hedge

  # Fitness evaluation
  fitness:
    weights:
      regime_performance: 0.4
      robustness: 0.3
      novelty: 0.2
      efficiency: 0.1
    thresholds:
      min_robustness: 0.7
      min_novelty: 0.5
      min_efficiency: 0.8
    regime_weights:
      volatility: 0.3
      trend_strength: 0.3
      volume_profile: 0.2
      correlation: 0.2
    regime_change_thresholds:
      volatility: 0.2
      trend: 0.3
      volume: 0.25

  # Resource management
  resources:
    gpu:
      max_memory_per_pod: 2048  # MB
      max_concurrent_pods: 10
      memory_threshold: 0.8
    cpu:
      max_threads_per_pod: 4
      max_concurrent_pods: 50
      thread_threshold: 0.8
    memory:
      max_memory_per_pod: 512  # MB
      memory_threshold: 0.8

  # Safety and monitoring
  safety:
    max_drawdown: 0.1
    max_position_size: 1.0
    min_confidence: 0.7
    max_leverage: 3.0
    stop_loss_threshold: 0.05
    take_profit_threshold: 0.1
    max_correlation: 0.8
    min_diversification: 0.3

  # Communication and coordination
  communication:
    inter_pod_latency: 0.001  # seconds
    max_message_size: 1024  # bytes
    heartbeat_interval: 1.0  # seconds
    timeout_threshold: 5.0  # seconds
    retry_attempts: 3
    backoff_factor: 1.5

  # Logging and monitoring
  logging:
    level: INFO
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file_rotation: 86400  # 24 hours
    max_file_size: 10485760  # 10 MB
    retention_days: 30
    metrics_interval: 60  # seconds

  # Performance optimization
  optimization:
    batch_size: 100
    cache_size: 1000
    prefetch_size: 50
    compression_level: 6
    max_parallel_operations: 10
    optimization_interval: 3600  # 1 hour

  # Market regime detection
  regime_detection:
    window_size: 1000
    min_regime_confidence: 0.7
    regime_memory_size: 100
    regime_merge_threshold: 0.8
    regime_split_threshold: 0.3
    regime_stability_threshold: 0.6

  # Mutation strategies
  mutation_strategies:
    core_math:
      mutation_rate: 0.05
      crossover_rate: 0.7
      selection_pressure: 0.8
      max_depth: 10
      max_operations: 100
    indicators:
      mutation_rate: 0.1
      crossover_rate: 0.6
      selection_pressure: 0.7
      max_parameters: 5
      max_combinations: 10
    strategy:
      mutation_rate: 0.15
      crossover_rate: 0.5
      selection_pressure: 0.6
      max_rules: 20
      max_conditions: 5

  # Sandbox environment
  sandbox:
    max_trials: 1000
    min_trial_duration: 3600  # 1 hour
    max_trial_duration: 86400  # 24 hours
    validation_threshold: 0.7
    rollback_threshold: 0.3
    max_concurrent_trials: 10
    trial_memory_size: 1000

# Adaptive Profit Chain Framework Configuration

# Formality stretching parameters for different market regimes
formality_stretching:
  high_vol:
    profit_multiplier: 1.5
    stop_multiplier: 1.2
    bucket_tolerance: 0.15
    min_confidence: 0.7
    volume_threshold: 1.3
    
  rangebound:
    profit_multiplier: 1.0
    stop_multiplier: 1.0
    bucket_tolerance: 0.2
    min_confidence: 0.6
    volume_threshold: 1.0
    
  trending:
    profit_multiplier: 1.3
    stop_multiplier: 1.1
    bucket_tolerance: 0.18
    min_confidence: 0.65
    volume_threshold: 1.2
    
  breakout:
    profit_multiplier: 1.4
    stop_multiplier: 1.15
    bucket_tolerance: 0.16
    min_confidence: 0.68
    volume_threshold: 1.25
    
  consolidation:
    profit_multiplier: 0.8
    stop_multiplier: 0.9
    bucket_tolerance: 0.25
    min_confidence: 0.55
    volume_threshold: 0.9

# Spectral analysis parameters
spectral_analysis:
  min_period: 2
  max_period: 100
  min_confidence: 0.6
  peak_height_threshold: 0.1
  overlap_tolerance: 0.5
  max_buckets: 50

# Profit chain parameters
profit_chains:
  max_chains: 10
  min_chain_length: 1
  max_chain_length: 5
  min_profit_threshold: 0.001
  max_risk_ratio: 3.0
  min_volume_requirement: 0.8

# Backtesting parameters
backtesting:
  window_size: 50
  reinit_interval: 20
  min_data_points: 100
  performance_metrics:
    - total_trades
    - win_rate
    - avg_profit
    - total_return
    - max_profit
    - max_loss
    - sharpe_ratio

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "apcf_system.log"
  max_size: 10485760  # 10MB
  backup_count: 5 