monitoring:
  system_metrics:
    cpu:
      enabled: true
      threshold: 80
      window_size: 60
      alert_threshold: 90
      collection_interval: 5

    memory:
      enabled: true
      threshold: 80
      window_size: 60
      alert_threshold: 90
      collection_interval: 5

    disk:
      enabled: true
      threshold: 80
      window_size: 60
      alert_threshold: 90
      collection_interval: 300

    network:
      enabled: true
      bandwidth_threshold_bps: 1000000
      latency_threshold: 100
      packet_loss_threshold: 0.01
      collection_interval: 5

  performance_metrics:
    latency:
      enabled: true
      threshold: 100
      window_size: 60
      alert_threshold: 200
      collection_interval: 1

    throughput:
      enabled: true
      threshold: 1000
      window_size: 60
      alert_threshold: 2000
      collection_interval: 1

    error_rate:
      enabled: true
      threshold: 0.01
      window_size: 60
      alert_threshold: 0.05
      collection_interval: 1

  trading_metrics:
    profit_loss:
      enabled: true
      threshold: -0.02
      window_size: 100
      alert_threshold: -0.05
      collection_interval: 1

    win_rate:
      enabled: true
      threshold: 0.5
      window_size: 100
      alert_threshold: 0.4
      collection_interval: 1

    drawdown:
      enabled: true
      threshold: 0.1
      window_size: 100
      alert_threshold: 0.15
      collection_interval: 1

  pattern_metrics:
    coherence:
      enabled: true
      threshold: 0.7
      window_size: 100
      alert_threshold: 0.5
      collection_interval: 1

    homeostasis:
      enabled: true
      threshold: 0.7
      window_size: 100
      alert_threshold: 0.5
      collection_interval: 1

    entropy:
      enabled: true
      threshold: 0.5
      window_size: 100
      alert_threshold: 0.7
      collection_interval: 1

  market_metrics:
    volatility:
      enabled: true
      threshold: 0.5
      window_size: 30
      alert_threshold: 0.7
      collection_interval: 1

    liquidity:
      enabled: true
      threshold: 1000000
      window_size: 20
      alert_threshold: 500000
      collection_interval: 1

    whale_activity:
      enabled: true
      threshold: 500000
      window_size: 30
      alert_threshold: 1000000
      collection_interval: 1

  logging:
    enabled: true
    level: "INFO"
    file: "logs/tesseract.log"
    max_size: 10485760
    backup_count: 5
    use_rotating_handler: true
    debug_log_enabled: false
    structured_output: true

  alerts:
    enabled: true
    rate_limit_seconds: 60
    per_channel_limits:
      slack: 10
      telegram: 5
      webhook: 3
    notification_channels:
      email:
        enabled: true
        smtp_server: "smtp.gmail.com"
        smtp_port: 587
        use_tls: true
        sender_email: "alerts@tesseract.com"
        recipient_emails: ["admin@tesseract.com"]

      slack:
        enabled: true
        webhook_url: "https://hooks.slack.com/services/xxx/yyy/zzz"
        channel: "#tesseract-alerts"

      telegram:
        enabled: true
        bot_token: "xxx:yyy"
        chat_id: "123456789"

      webhook:
        enabled: true
        url: "https://api.tesseract.com/webhook"
        method: "POST"
        headers:
          Authorization: "Bearer xxx"
          Content-Type: "application/json"

  dashboard:
    enabled: true
    port: 3000
    theme: "dark"
    update_rate: 1000
    metrics:
      system: true
      performance: true
      trading: true
      pattern: true
      market: true
    visualization:
      show_grid: true
      show_labels: true
      show_timestamps: true
      color_scheme: "quantum"

  # New section for indexed risk metrics
  indexed_metrics:
    enabled: true
    baseline_reset_frequency: 100  # Reset baseline every 100 ticks
    metrics_to_index:
      - var_95
      - var_99
      - cvar_95
      - fhs_var
      - garch_var
      - expected_shortfall
      - median_shortfall
      - sharpe_ratio
      - sortino_ratio
      - coherence
      - homeostasis
      - entropy
    alert_thresholds:
      var_indexed_threshold: 1.5  # Alert if VaR is 50% higher than baseline
      coherence_indexed_threshold: 0.8  # Alert if coherence drops 20% below baseline
      sharpe_indexed_threshold: 0.9  # Alert if Sharpe ratio drops 10% below baseline
      entropy_indexed_threshold: 1.3  # Alert if entropy increases 30% above baseline 